#
# purpose:  Docker-compose yaml file for test mysql server
# author:   Pierre Veelen <pierre@pvln.nl>
# version:  2017-10-01 initial version
#

version: "2"

services: 

    mysqlserver:
        build: 
            context: ../services/${MY_PLATFORM}/mysql_5.5
            dockerfile: Dockerfile
        ports:
        - "3306:3306"
        volumes:
        - ${MY_MYSQL_DATA_VOLUME}:/var/lib/mysql

