#
# file:     apache2.yml
# purpose:  Docker-compose yaml file for test apache2 image
# author:   Pierre Veelen <pierre@pvln.nl>
# version:  2017-10-01 initial version
#           2018-06-09 added additional variables
#           2018-06-12 added log volume
#
# required environment variables: 
#           ${MY_PLATFORM}
#           ${MY_CONTAINER_NAME}
#           ${MY_DOCKERFILE}
#           ${MY_LEVEL}
#           ${MY_BUILDER}
#           ${MY_WEB_DATA_VOLUME}
#           ${MY_WEB_LOG_VOLUME}

version: "3"

services: 

    apache2service:
        #what to build and where to find it
        #
        build: 
            context: ../../services/${MY_PLATFORM}/${MY_CONTAINER_NAME}
            dockerfile: ${MY_DOCKERFILE}

        #how to name and tag the image
        #
        #for example pvln/rpi3-lvl1-apache2:1.0
        #
        image: ${MY_BUILDER}/${MY_PLATFORM}-${MY_LEVEL}-${MY_CONTAINER_NAME}:${MY_VERSION}

        # restart the container under any circumstance
        #
        #restart: always

        # port on host : port on container
        #
        ports:
        -"80:80"

        # volume on host : volume in container
        #
        volumes:
        - APACHE2_DATA_VOLUME:/var/www/html
        - APACHE2_LOG_VOLUME:/var/log/apache2

        # values to pass to the container as environment variable
        # only available when container is run, not when container is build
        #        
        #environment:

volumes:
    # volume with persistent data
    #
    APACHE2_DATA_VOLUME:
        driver_opts:
            type: none 
            device: ${MY_WEB_DATA_VOLUME}
            o: bind
    APACHE2_LOG_VOLUME:
        driver_opts:
            type: none 
            device: ${MY_WEB_LOG_VOLUME}
            o: bind
