#
# file:     baseline.yml
# purpose:  Docker-compose yaml file for test baseline image
# author:   Pierre Veelen <pierre@pvln.nl>
# version:  2017-10-01 initial version
#           2018-06-09 added additional variables
#
# required: ${MY_PLATFORM}
#           ${MY_CONTAINER_NAME}
#           ${MY_DOCKERFILE}
#           ${MY_LEVEL}
#           ${MY_BUILDER}
#           ${MY_VERSION}

version: "3"

services: 

    baselineservice:
        #what to build and where to find it
        #
        build:
           context: ../../services/${MY_PLATFORM}/${MY_CONTAINER_NAME}
           dockerfile: ${MY_DOCKERFILE}
           
        #how to name and tag the image
        #  
        image: ${MY_BUILDER}/${MY_PLATFORM}-${MY_LEVEL}-${MY_CONTAINER_NAME}:${MY_VERSION}

        # restart the container under any circumstance
        #
        #restart: always
