#
# file:     mysql-tst.yml
# purpose:  Docker-compose yaml file for test mysql server
# author:   Pierre Veelen <pierre@pvln.nl>
# version:  2017-10-01 initial version
#

version: "2"

services: 

    mysqlserver:
        #what to build and where to find it
        #    
        build: 
            context: ../../services/${MY_PLATFORM}/${MY_CONTAINER_NAME}
            dockerfile: Dockerfile
            
        #how to name and tag the image
        #
        #for example pvln/rpi3-lvl1-mysql:1.0
        #        
        image: ${MY_BUILDER}/${MY_PLATFORM}-${MY-LEVEL}-${MY_CONTAINER_NAME}:1.0

        # port on host : port on container
        #        
        ports:
        - "3306:3306"

        # volume on host : volume in container
        #
        volumes:
        - ${MY_MYSQL_DATA_VOLUME}:/var/lib/mysql
