#
# file:     php_5.6.yml
# purpose:  Docker-compose yaml file for test php5 image
# author:   Pierre Veelen <pierre@pvln.nl>
# version:  2017-10-01 initial version
#
# required environment variables: 
#           ${MY_PLATFORM}
#           ${MY_CONTAINER_NAME}
#           ${MY_DOCKERFILE}
#           ${MY_LEVEL}
#           ${MY_BUILDER}
#           ${MY_PHP5_LOG_VOLUME}
#           ${MY_PHP5_DATA_VOLUME}

version: "3"

services: 

    php_5.6_service:

        #what to build and where to find it
        #
        build:
            context: ../../services/${MY_PLATFORM}/${MY_CONTAINER_NAME}
            dockerfile: ${MY_DOCKERFILE}

        #how to name and tag the image
        #
        #for example pvln/rpi3-lvl1-php5.6:1.0
        #
        image: ${MY_BUILDER}/${MY_PLATFORM}-${MY_LEVEL}-${MY_CONTAINER_NAME}:${MY_VERSION}

        # restart the container under any circumstance
        #
        #restart: always

        # port on host : port on container
        #
        # ATTENTION: if ports are defined in lower level containers,
        #            they have to be defined again in this container
        #
        ports:
        # for apache2 layer
        - "80:80"

        # volume on host : volume in container
        #
        volumes:
        # for apache2 layer
        - PHP_5.6_DATA_VOLUME:/var/www/html
        - PHP_5.6_LOG_VOLUME:/var/log/apache2

        # values to pass to the container as environment variable
        # only available when container is run, not when container is build
        #
        #environment:

volumes:
    # volume with persistent data
    #
    PHP_5.6_DATA_VOLUME:
        driver_opts:
            type: none 
            device: ${MY_WEB_DATA_VOLUME}
            o: bind
    PHP_5.6_LOG_VOLUME:
        driver_opts:
            type: none 
            device: ${MY_WEB_LOG_VOLUME}
            o: bind
